# Generated by Django 2.2.24 on 2022-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userbase_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
