# Generated by Django 2.2.24 on 2022-01-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userbase_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='is_active',
            new_name='active',
        ),
    ]
