# Generated by Django 2.2.24 on 2022-01-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220130_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
