# Generated by Django 2.2.24 on 2022-01-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220130_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbase',
            name='active',
        ),
        migrations.AddField(
            model_name='userbase',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
