# Generated by Django 2.2.24 on 2022-01-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220130_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='is_active',
            new_name='is_activate',
        ),
    ]
